# Generated by Django 4.2.25 on 2025-10-22 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_user_category',
        ),
    ]
